version: "1"

services:
  postgres:
    image: bitnami/postgresql:15.3.0
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=q
      - POSTGRESQL_TIMEZONE=Europe/Istanbul
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=tr-TR
    restart: always

#  elasticsearch:
#    container_name: elasticsearch
#    image: bitnami/elasticsearch:8.11.3
#    ports:
#      - "9201:9200"
#    restart: always